// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fleeting.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFleetingNote = `-- name: CreateFleetingNote :one
INSERT INTO blog.fleeting (date, tag_id, user_id)
    VALUES ($1, (
            SELECT
                id
            FROM
                blog.tags
            WHERE
                name = $2), $3)
RETURNING
    id, date, tag_id, created_at, user_id
`

type CreateFleetingNoteParams struct {
	Date    string
	TagName string
	UserID  pgtype.UUID
}

func (q *Queries) CreateFleetingNote(ctx context.Context, arg CreateFleetingNoteParams) (BlogFleeting, error) {
	row := q.db.QueryRow(ctx, createFleetingNote, arg.Date, arg.TagName, arg.UserID)
	var i BlogFleeting
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.TagID,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
