// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogCasbinRule struct {
	ID    string
	PType pgtype.Text
	V0    pgtype.Text
	V1    pgtype.Text
	V2    pgtype.Text
	V3    pgtype.Text
	V4    pgtype.Text
	V5    pgtype.Text
}

type BlogFleeting struct {
	ID        pgtype.UUID
	Date      string
	TagID     int32
	CreatedAt pgtype.Timestamp
	UserID    pgtype.UUID
}

type BlogSession struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type BlogTag struct {
	ID   int32
	Name string
}

type BlogUser struct {
	ID        pgtype.UUID
	Auth0Sub  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BlogUserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	LastToken pgtype.Text
	UpdatedAt pgtype.Timestamptz
}
