// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogCasbinRule struct {
	ID    string
	PType pgtype.Text
	V0    pgtype.Text
	V1    pgtype.Text
	V2    pgtype.Text
	V3    pgtype.Text
	V4    pgtype.Text
	V5    pgtype.Text
}

type BlogDisplayTag struct {
	TagID        pgtype.UUID
	BgColor      string
	TextColor    string
	BorderColors []string
	Bold         bool
	Italic       bool
	Underline    bool
	Font         string
}

type BlogFleeting struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UserID    pgtype.UUID
	TagIds    []pgtype.UUID
	Content   string
	DeletedAt pgtype.Timestamptz
}

type BlogNoteComponent struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ParentID  pgtype.UUID
	Name      string
	Pattern   string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BlogSession struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type BlogTag struct {
	Name   string
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type BlogUser struct {
	ID        pgtype.UUID
	Auth0Sub  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BlogUserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	LastToken pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

type TagIDMap struct {
	OldID int32
	NewID pgtype.UUID
}
