version: "3"

tasks:
  dev:
    desc: "Run full development environment"
    run: once
    deps:
      # - watch:templ-local
      # - watch:templ-shared
      # - watch:tailwind
      # - run:go
      - run:air

  clean:
    desc: "Clean up all dev processes and ports"
    cmds:
      - killall -9 main 2>/dev/null || true
      - killall -9 air 2>/dev/null || true
      - lsof -ti:4444 | xargs kill -9 2>/dev/null || true
      - rm -rf ./tmp
      - echo "Cleaned up processes on port 4444"

  run:air:
    cmds:
      - air

  run:go:
    cmds:
      - go run ./cmd/

  templ:
    desc: "Generate templ files once"
    cmds:
      - templ generate

  tailwind:
    desc: "Build tailwind CSS once"
    cmds:
      - >
        npx tailwindcss -c ./tailwind.config.js -i ./ui/static/globals.css -o ./ui/static/css/output.css

  build:
    desc: "Run templ and tailwind once"
    deps:
      - templ
      - tailwind

  watch:templ-local:
    sources:
      - "./**/*.templ"
    cmds:
      - templ generate --watch

  watch:templ-shared:
    dir: ../../shared/gencomponents/components
    sources:
      - "./**/*.templ"
    cmds:
      - templ generate --watch

  watch:tailwind:
    cmds:
      - >
        npx tailwindcss -c ./tailwind.config.js -i ./ui/static/globals.css -o ./ui/static/css/output.css --watch
